
build: 
	nasm -f elf p5f.asm
	ld -m elf_i386 p5f.o -o ../../bin/practica5.exe ../../lib/libpc_io.a


builda: 
	nasm -f elf p5a.asm
	ld -m elf_i386 p5a.o -o ../../bin/practica5.exe ../../lib/libpc_io.a


buildb: 
	nasm -f elf p5b.asm
	ld -m elf_i386 p5b.o -o ../../bin/practica5.exe ../../lib/libpc_io.a


buildc: 
	nasm -f elf p5c.asm
	ld -m elf_i386 p5c.o -o ../../bin/practica5.exe ../../lib/libpc_io.a


buildd: 
	nasm -f elf p5d.asm
	ld -m elf_i386 p5d.o -o ../../bin/practica5.exe ../../lib/libpc_io.a

builde: 
	nasm -f elf p5e.asm
	ld -m elf_i386 p5e.o -o ../../bin/practica5.exe ../../lib/libpc_io.a

buildf: 
	nasm -f elf p5f.asm
	ld -m elf_i386 p5f.o -o ../../bin/practica5.exe ../../lib/libpc_io.a

run:
	./../../bin/practica5.exe