
build: 
	nasm -f elf p5f.asm
	ld -m elf_i386 p5f.o -o ../../bin/practica5.exe ../../lib/libpc_io.a
run:
	./../../bin/practica5.exe

builda: 
	nasm -f elf p5a.asm
	ld -m elf_i386 p5a.o -o ../../bin/practica5.exe ../../lib/libpc_io.a
runa:
	./../../bin/practica5.exe

buildb: 
	nasm -f elf p5b.asm
	ld -m elf_i386 p5b.o -o ../../bin/practica5.exe ../../lib/libpc_io.a
runb:
	./../../bin/practica5.exe

buildc: 
	nasm -f elf p5c.asm
	ld -m elf_i386 p5c.o -o ../../bin/practica5.exe ../../lib/libpc_io.a
runc:
	./../../bin/practica5.exe

buildd: 
	nasm -f elf p5d.asm
	ld -m elf_i386 p5d.o -o ../../bin/practica5.exe ../../lib/libpc_io.a
rund:
	./../../bin/practica5.exe

builde: 
	nasm -f elf p5e.asm
	ld -m elf_i386 p5e.o -o ../../bin/practica5.exe ../../lib/libpc_io.a
rune:
	./../../bin/practica5.exe

buildf: 
	nasm -f elf p5f.asm
	ld -m elf_i386 p5f.o -o ../../bin/practica5.exe ../../lib/libpc_io.a
runf:
	./../../bin/practica5.exe